"""full redesign schema - timeline, service tags, expanded settings

Revision ID: 08097a6acfd2
Revises: 87fbd27d7404
Create Date: 2026-08-09 02:37:19.296620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08097a6acfd2'
down_revision: Union[str, None] = '87fbd27d7404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_items_id'), 'timeline_items', ['id'], unique=False)
    op.add_column('services', sa.Column('tags', sa.String(length=200), nullable=True))
    op.add_column('site_settings', sa.Column('hero_eyebrow', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('availability_label', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('hero_description', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('hero_badges', sa.String(length=200), nullable=True))
    op.add_column('site_settings', sa.Column('photo_stamp_text', sa.String(length=60), nullable=True))
    op.add_column('site_settings', sa.Column('hero_scribble', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('marquee_skills', sa.String(length=400), nullable=True))
    op.add_column('site_settings', sa.Column('about_statement', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('about_paragraph', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('about_focus', sa.String(length=80), nullable=True))
    op.add_column('site_settings', sa.Column('about_status', sa.String(length=80), nullable=True))
    op.add_column('site_settings', sa.Column('skills_heading', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('skills_intro', sa.String(length=300), nullable=True))
    op.add_column('site_settings', sa.Column('work_heading', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('work_intro', sa.String(length=300), nullable=True))
    op.add_column('site_settings', sa.Column('journey_heading', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('journey_note', sa.String(length=300), nullable=True))
    op.add_column('site_settings', sa.Column('ai_heading', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('ai_note', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('contact_eyebrow', sa.String(length=60), nullable=True))
    op.add_column('site_settings', sa.Column('contact_heading', sa.String(length=100), nullable=True))
    op.add_column('site_settings', sa.Column('social_github', sa.String(length=300), nullable=True))
    op.add_column('site_settings', sa.Column('social_linkedin', sa.String(length=300), nullable=True))
    op.add_column('site_settings', sa.Column('social_instagram', sa.String(length=300), nullable=True))
    op.add_column('site_settings', sa.Column('social_x', sa.String(length=300), nullable=True))
    op.drop_column('site_settings', 'hero_tagline')
    op.drop_column('site_settings', 'hero_bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('hero_bio', sa.TEXT(), nullable=True))
    op.add_column('site_settings', sa.Column('hero_tagline', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('site_settings', 'social_x')
    op.drop_column('site_settings', 'social_instagram')
    op.drop_column('site_settings', 'social_linkedin')
    op.drop_column('site_settings', 'social_github')
    op.drop_column('site_settings', 'contact_heading')
    op.drop_column('site_settings', 'contact_eyebrow')
    op.drop_column('site_settings', 'ai_note')
    op.drop_column('site_settings', 'ai_heading')
    op.drop_column('site_settings', 'journey_note')
    op.drop_column('site_settings', 'journey_heading')
    op.drop_column('site_settings', 'work_intro')
    op.drop_column('site_settings', 'work_heading')
    op.drop_column('site_settings', 'skills_intro')
    op.drop_column('site_settings', 'skills_heading')
    op.drop_column('site_settings', 'about_status')
    op.drop_column('site_settings', 'about_focus')
    op.drop_column('site_settings', 'about_paragraph')
    op.drop_column('site_settings', 'about_statement')
    op.drop_column('site_settings', 'marquee_skills')
    op.drop_column('site_settings', 'hero_scribble')
    op.drop_column('site_settings', 'photo_stamp_text')
    op.drop_column('site_settings', 'hero_badges')
    op.drop_column('site_settings', 'hero_description')
    op.drop_column('site_settings', 'availability_label')
    op.drop_column('site_settings', 'hero_eyebrow')
    op.drop_column('services', 'tags')
    op.drop_index(op.f('ix_timeline_items_id'), table_name='timeline_items')
    op.drop_table('timeline_items')
    # ### end Alembic commands ###
