"""add services table and expand site settings

Revision ID: 7a5cecce7eea
Revises: 9f7fadf2d12f
Create Date: 2026-08-07 11:00:57.032094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5cecce7eea'
down_revision: Union[str, None] = '9f7fadf2d12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('icon_key', sa.String(length=30), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.add_column('site_settings', sa.Column('hero_first_name', sa.String(length=50), nullable=True))
    op.add_column('site_settings', sa.Column('hero_last_name', sa.String(length=50), nullable=True))
    op.add_column('site_settings', sa.Column('hero_tagline', sa.String(length=150), nullable=True))
    op.add_column('site_settings', sa.Column('hero_bio', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('available_for_work', sa.Boolean(), nullable=True))
    op.add_column('site_settings', sa.Column('contact_email', sa.String(length=150), nullable=True))
    op.add_column('site_settings', sa.Column('contact_location', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'contact_location')
    op.drop_column('site_settings', 'contact_email')
    op.drop_column('site_settings', 'available_for_work')
    op.drop_column('site_settings', 'hero_bio')
    op.drop_column('site_settings', 'hero_tagline')
    op.drop_column('site_settings', 'hero_last_name')
    op.drop_column('site_settings', 'hero_first_name')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
