"""add contact phone field

Revision ID: 87fbd27d7404
Revises: 7a5cecce7eea
Create Date: 2026-08-08 12:56:04.037913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fbd27d7404'
down_revision: Union[str, None] = '7a5cecce7eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'contact_phone')
    # ### end Alembic commands ###
