"""add site images and settings

Revision ID: 9f7fadf2d12f
Revises: cfdf2825f1a7
Create Date: 2026-08-07 02:16:43.634733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7fadf2d12f'
down_revision: Union[str, None] = 'cfdf2825f1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_images_id'), 'site_images', ['id'], unique=False)
    op.create_index(op.f('ix_site_images_slot'), 'site_images', ['slot'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bg_color', sa.String(length=20), nullable=True),
    sa.Column('ink_color', sa.String(length=20), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('font_pair', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_site_images_slot'), table_name='site_images')
    op.drop_index(op.f('ix_site_images_id'), table_name='site_images')
    op.drop_table('site_images')
    # ### end Alembic commands ###
