"""add font scale setting

Revision ID: a603563900d6
Revises: 08097a6acfd2
Create Date: 2026-08-11 01:27:45.819551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a603563900d6'
down_revision: Union[str, None] = '08097a6acfd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('font_scale', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'font_scale')
    # ### end Alembic commands ###
